export const GET_POSTS_REQUEST="GET_POSTS_REQUEST"
export const GET_POSTS_SUCCESS="GET_POSTS_SUCCESS"
export const GET_POSTS_FAILURE="GET_POSTS_FAILURE"

export const CREATE_POST_REQUEST='CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS='CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE='CREATE_POST_FAILURE'

export const LOGIN_REQUEST='LOGIN_REQUEST'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILURE='LOGIN_FAILURE'

export const LOGOUT_REQUEST='LOGOUT_REQUEST'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const LOGOUT_FAILURE='LOGOUT_FAILURE'

export const CREATE_USER_REQUEST ='CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS='CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE='CREATE_USER_FAILURE'